export const CASE_STATUS = {
  SUBMITTED: 'SUBMITTED',
  AI_INVESTIGATING: 'AI_INVESTIGATING',
  AI_READY: 'AI_READY',
  UNDER_REVIEW: 'UNDER_REVIEW',
  MORE_INFO_REQUIRED: 'MORE_INFO_REQUIRED',
  ESCALATED: 'ESCALATED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  RESOLVED: 'RESOLVED'
};

const VALID_TRANSITIONS = {
  [CASE_STATUS.SUBMITTED]: [CASE_STATUS.AI_INVESTIGATING, CASE_STATUS.MANUAL_REVIEW],
  [CASE_STATUS.AI_INVESTIGATING]: [CASE_STATUS.AI_READY, CASE_STATUS.MANUAL_REVIEW],
  [CASE_STATUS.AI_READY]: [CASE_STATUS.UNDER_REVIEW, CASE_STATUS.MANUAL_REVIEW, CASE_STATUS.RESOLVED, CASE_STATUS.MORE_INFO_REQUIRED, CASE_STATUS.ESCALATED],
  [CASE_STATUS.UNDER_REVIEW]: [CASE_STATUS.MORE_INFO_REQUIRED, CASE_STATUS.ESCALATED, CASE_STATUS.RESOLVED, CASE_STATUS.MANUAL_REVIEW],
  [CASE_STATUS.MORE_INFO_REQUIRED]: [CASE_STATUS.UNDER_REVIEW, CASE_STATUS.MANUAL_REVIEW],
  [CASE_STATUS.ESCALATED]: [CASE_STATUS.RESOLVED, CASE_STATUS.MANUAL_REVIEW],
  [CASE_STATUS.MANUAL_REVIEW]: [CASE_STATUS.RESOLVED, CASE_STATUS.MORE_INFO_REQUIRED, CASE_STATUS.ESCALATED],
  [CASE_STATUS.RESOLVED]: [] // Terminal state
};

/**
 * Validates whether a case status transition is allowed.
 * @param {string} fromStatus 
 * @param {string} toStatus 
 * @returns {boolean}
 */
export const isValidTransition = (fromStatus, toStatus) => {
  if (fromStatus === toStatus) return true;
  const allowed = VALID_TRANSITIONS[fromStatus];
  return allowed ? allowed.includes(toStatus) : false;
};
